### PR TITLE
1.14 compability

### LINKED ISSUE #3: 1.14 compability
Minecraft 1.14 brings some new biomes, and MinedMap stop working.
```Generating /var/www/map/data/map/0/r.-1.1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-1.1.mca...
Failed to generate /var/www/map/data/map/0/r.-1.1.png: assertValue failed
Generating /var/www/map/data/map/0/r.-2.-1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-2.-1.mca...
Failed to generate /var/www/map/data/map/0/r.-2.-1.png: assertValue failed
Generating /var/www/map/data/map/0/r.-2.-2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-2.-2.mca...
Failed to generate /var/www/map/data/map/0/r.-2.-2.png: assertValue failed
Generating /var/www/map/data/map/0/r.1.1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.1.1.mca...
Failed to generate /var/www/map/data/map/0/r.1.1.png: assertValue failed
Generating /var/www/map/data/map/0/r.1.2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.1.2.mca...
Generating /var/www/map/data/map/0/r.1.-1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.1.-1.mca...
Failed to generate /var/www/map/data/map/0/r.1.-1.png: assertValue failed
Generating /var/www/map/data/map/0/r.2.0.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.2.0.mca...
Generating /var/www/map/data/map/0/r.0.-1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.0.-1.mca...
Failed to generate /var/www/map/data/map/0/r.0.-1.png: assertValue failed
Generating /var/www/map/data/map/0/r.2.2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.2.2.mca...
Generating /var/www/map/data/map/0/r.-1.0.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-1.0.mca...
Failed to generate /var/www/map/data/map/0/r.-1.0.png: assertValue failed
Generating /var/www/map/data/map/0/r.-2.1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-2.1.mca...
Failed to generate /var/www/map/data/map/0/r.-2.1.png: assertValue failed
Generating /var/www/map/data/map/0/r.2.-1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.2.-1.mca...
Generating /var/www/map/data/map/0/r.0.-2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.0.-2.mca...
Failed to generate /var/www/map/data/map/0/r.0.-2.png: corrupt biome data
Generating /var/www/map/data/map/0/r.1.0.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.1.0.mca...
Failed to generate /var/www/map/data/map/0/r.1.0.png: assertValue failed
Generating /var/www/map/data/map/0/r.-1.-1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-1.-1.mca...
Failed to generate /var/www/map/data/map/0/r.-1.-1.png: assertValue failed
Generating /var/www/map/data/map/0/r.-1.2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-1.2.mca...
Generating /var/www/map/data/map/0/r.0.1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.0.1.mca...
Failed to generate /var/www/map/data/map/0/r.0.1.png: assertValue failed
Generating /var/www/map/data/map/0/r.0.2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.0.2.mca...
Generating /var/www/map/data/map/0/r.-2.0.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-2.0.mca...
Failed to generate /var/www/map/data/map/0/r.-2.0.png: corrupt biome data
Generating /var/www/map/data/map/0/r.2.1.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.2.1.mca...
Generating /var/www/map/data/map/0/r.0.0.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.0.0.mca...
Failed to generate /var/www/map/data/map/0/r.0.0.png: assertValue failed
Generating /var/www/map/data/map/0/r.-2.2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-2.2.mca...
Generating /var/www/map/data/map/0/r.1.-2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.1.-2.mca...
Failed to generate /var/www/map/data/map/0/r.1.-2.png: assertValue failed
Generating /var/www/map/data/map/0/r.-1.-2.png from /faster/pufferd/servers/2f162c95-27ae-4f64-8284-3409d3cabcad/world/region/r.-1.-2.mca...
Failed to generate /var/www/map/data/map/0/r.-1.-2.png: corrupt biome data
```

### PR DESCRIPTION
**Pull request by roman901**
This PR resolves #3

### CODE REVIEW

**Comment by NeoRaider** [comment]
Ooh thanks! Will review on the weekend.

**Comment by NeoRaider** [comment]
Could you provide me with a region file that exhibits the issues you fix in "Don't fall on empty Sections" and "Ignore chunks without sections"?

**Comment by roman901** [comment]
In 1.14 Mojang writes empty Section with Y=255 in every chunk (I don't realise why). And I also found some chunks in the world, which also contains no sections at all, and other tags like blocks/light are also empty

**Comment by roman901** [comment]
About empty chunks: very often it generates between two biomes - chunk is exists, but has no sections.
image

**Comment by NeoRaider** [comment]
Thanks! I've merged your changes now, with a few adjustments:
- Chose different solutions for the empty section/empty chunk issues
- Decided against invisible glass (might implement semi-transparent blocks at some point)
- Added the remaining new blocks (can be found in `assets/minecraft/blockstates` in the unpacked Minecraft jar), used different textures in some cases
- Added a quirk for the stone_slab rename

**Comment by roman901** [comment]
Sorry for necroposting, but in latest Paper's commits I found a note about proto chunks. https://github.com/PaperMC/Paper/commit/de002d43b35cc4ffff6bdbf3e8623390669c9689

Maybe broken chunks at pic above is a proto chunks.

**Pull request closed without merging**
